/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelleryshop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author my pc
 */
public class Analytics extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Analytics() {
        initComponents();
        dpicker1.setVisible(false);
        dpicker2.setVisible(false);
        jLabel3.setVisible(false);
        yr.setVisible(false);
        jPanel1.setVisible(false);
        conn = db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchase = new javax.swing.JRadioButton();
        sales = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        monthly = new javax.swing.JRadioButton();
        yearly = new javax.swing.JRadioButton();
        dpicker2 = new org.jdesktop.swingx.JXDatePicker();
        yr = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dpicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        purchase.setText("Purchase history");
        purchase.setOpaque(false);
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });
        getContentPane().add(purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        sales.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sales.setText("Sales History");
        sales.setOpaque(false);
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        getContentPane().add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monthly.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthly.setText("Monthly Sales");
        monthly.setOpaque(false);
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        jPanel1.add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        yearly.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearly.setText("Yearly Sales");
        yearly.setOpaque(false);
        yearly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyActionPerformed(evt);
            }
        });
        jPanel1.add(yearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        dpicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpicker2ActionPerformed(evt);
            }
        });
        jPanel1.add(dpicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 30));

        yr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yrKeyReleased(evt);
            }
        });
        jPanel1.add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 94, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 696, 223));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total Sales :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 97, -1));

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotal.setText("jLabel2");
        jPanel1.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 101, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        dpicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpicker1ActionPerformed(evt);
            }
        });
        jPanel1.add(dpicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 87, 800, 500));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 870, 620));

        jMenu1.setText("File");

        jMenuItem1.setText("Home ");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Report Zone");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
       monthly.setSelected(true);
       yearly.setSelected(false);
       dpicker1.setVisible(true);
       dpicker2.setVisible(true);
       jLabel3.setVisible(true);
       yr.setVisible(false);
    }//GEN-LAST:event_monthlyActionPerformed

    private void yearlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyActionPerformed
       monthly.setSelected(false);
       yearly.setSelected(true);
       yr.setVisible(true);
       dpicker2.setVisible(false);
       jLabel3.setVisible(false);
       dpicker1.setVisible(false);
    }//GEN-LAST:event_yearlyActionPerformed

    private void dpicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpicker2ActionPerformed
        if(monthly.getText()=="Monthly Sales History")
        {
            monthlysales();
        }
        else if(monthly.getText()=="Monthly Purchase History")
        {
            System.out.println("In");
            monthlypurchase();
        }
        
    }//GEN-LAST:event_dpicker2ActionPerformed
    void monthlysales()
    {
        amt =0;
        Date s1 = dpicker1.getDate();
        DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String dat1 = d.format(s1);
        
        Date s2 = dpicker2.getDate();
        String dat2 = d.format(s2);
        
        try
        {
            String sql ="select * from bill where date between '"+dat1+"' and '"+dat2+"'";
           
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            while(rs.next())
            {
                System.out.println("i am in");
                amt = amt+Float.parseFloat(rs.getString("grandtotal"));
            }
            lbltotal.setText(String.valueOf(amt));
          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
    }
    void monthlypurchase()
    {
        amt =0;
        Date s1 = dpicker1.getDate();
        DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String dat1 = d.format(s1);
        
        Date s2 = dpicker2.getDate();
        String dat2 = d.format(s2);
        
        try
        {
            String sql ="select otype,metal,weight,priceper,qty,grandtotal,date from purchase where date between '"+dat1+"' and '"+dat2+"'";
           
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            while(rs.next())
            {
                System.out.println("i am in");
                amt = amt+Float.parseFloat(rs.getString("grandtotal"));
            }
            lbltotal.setText(String.valueOf(amt));
          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
        float amt =0;
    private void yrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yrKeyReleased
        amt =0;
        int l = yr.getText().length();
        if(l==4)
       {
           if(yearly.getText()=="Yearly Sales History")
           {
               try
            {
            String sql ="select * from bill where date LIKE '"+yr.getText()+"-%-%'";
           System.out.println(sql);
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            while(rs.next())
            {
                System.out.println("i am in");
                amt = amt+Float.parseFloat(rs.getString("grandtotal"));
            }
            lbltotal.setText(String.valueOf(amt));
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
           }
           else if((yearly.getText()=="Yearly Purchase History"))
           {
               try
            {
            String sql ="select otype,metal,weight,priceper,qty,grandtotal,date from purchase where date LIKE '"+yr.getText()+"-%-%'";
           System.out.println(sql);
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst=conn.prepareStatement(sql);              
            rs = pst.executeQuery();
            while(rs.next())
            {
                System.out.println("i am in");
                amt = amt+Float.parseFloat(rs.getString("grandtotal"));
            }
            lbltotal.setText(String.valueOf(amt));
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
           
           }
           
       }
        
    }//GEN-LAST:event_yrKeyReleased

    private void dpicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpicker1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpicker1ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        Report r = new Report();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        purchase.setSelected(true);
        sales.setSelected(false);
        
        jPanel1.setVisible(true);
        monthly.setText("Monthly Purchase History");
        yearly.setText("Yearly Purchase History");
        
    }//GEN-LAST:event_purchaseActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        purchase.setSelected(false);
        sales.setSelected(true);
        
        jPanel1.setVisible(true);
        monthly.setText("Monthly Sales History");
        yearly.setText("Yearly Sales History");
    }//GEN-LAST:event_salesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dpicker1;
    private org.jdesktop.swingx.JXDatePicker dpicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JRadioButton monthly;
    private javax.swing.JRadioButton purchase;
    private javax.swing.JRadioButton sales;
    private javax.swing.JRadioButton yearly;
    private javax.swing.JTextField yr;
    // End of variables declaration//GEN-END:variables
}
