/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelleryshop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


public class CustomBill extends javax.swing.JFrame {

Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
float total =0;
    public CustomBill() {
        initComponents();
        
        conn=db.java_db();
        jLabel8.setVisible(false);
        jid.setVisible(false);
        getMaxId();
        //autodategemnerate
        Date date = Calendar.getInstance().getTime();
        DateFormat dateGet = new SimpleDateFormat("yyyy-MM-dd");
        String strDate = dateGet.format(date);
        cdate.setText(strDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grandtotal1 = new javax.swing.JTextField();
        cur6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        billno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cprice = new javax.swing.JTextField();
        metal = new javax.swing.JComboBox();
        cur = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cur1 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        cur2 = new javax.swing.JLabel();
        oprice = new javax.swing.JTextField();
        otype = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbutton = new javax.swing.JRadioButton();
        cbutton = new javax.swing.JRadioButton();
        jid = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cdate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cur3 = new javax.swing.JLabel();
        cur4 = new javax.swing.JLabel();
        mcharge = new javax.swing.JTextField();
        gst = new javax.swing.JTextField();
        cur5 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        clear = new javax.swing.JButton();
        gbill = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grandtotal1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grandtotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandtotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(grandtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 80, -1));

        cur6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur6.setText("GrandTotal :");
        getContentPane().add(cur6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 90, 22));

        TextArea1.setColumns(20);
        TextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 240, 340));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Customer Name :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Customer Phone Number :");

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        cnumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnumberKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 66, 540, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Bill no. :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 25, 65, -1));

        billno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(billno, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 22, 69, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Jewellery Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ornament Made Of:");

        cprice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpriceKeyReleased(evt);
            }
        });

        metal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        metal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gold", "Silver", "Platinum", "Bronze" }));
        metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metalActionPerformed(evt);
            }
        });

        cur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur.setText("Curent Price Of :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ornament Type :");

        cur1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur1.setText("Ornament Weight :");

        weight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                weightKeyReleased(evt);
            }
        });

        cur2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur2.setText("Ornament Price :");

        oprice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        otype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Jewellery Id :");

        rbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbutton.setText("Ready-made Order");
        rbutton.setOpaque(false);
        rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttonActionPerformed(evt);
            }
        });

        cbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbutton.setText("Custom Order");
        cbutton.setOpaque(false);
        cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuttonActionPerformed(evt);
            }
        });

        jid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cur2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oprice))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbutton))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbutton)
                                    .addComponent(metal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(otype))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cur1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(weight))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cur, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cprice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbutton)
                    .addComponent(cbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cur1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cur2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 200, 540, 220));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Date :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 65, 20));

        cdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(cdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 120, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cur3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur3.setText("GST %   :");
        jPanel3.add(cur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 28, -1, 22));

        cur4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur4.setText("Making Charges  % :");
        jPanel3.add(cur4, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 28, -1, 22));

        mcharge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mcharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mchargeKeyReleased(evt);
            }
        });
        jPanel3.add(mcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 29, 101, -1));

        gst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gstKeyReleased(evt);
            }
        });
        jPanel3.add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 29, 80, -1));

        cur5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cur5.setText("Jewellery Price:");
        jPanel3.add(cur5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 68, 90, 22));

        grandtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        grandtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandtotalActionPerformed(evt);
            }
        });
        jPanel3.add(grandtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 69, 80, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 53, 500, 10));

        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setText("New Bill");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 110, -1));

        gbill.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gbill.setText("Generate Bill");
        gbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbillActionPerformed(evt);
            }
        });
        jPanel3.add(gbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, -1));

        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setText("Add More");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 110, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 424, 540, 140));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 870, 580));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("File");

        jMenuItem1.setText("Home");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("ReportZone");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Logout");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     void getMaxId(){
    try{
      
       
            String sql= "select MAX(billno)+1 from billdetails";
            pst=conn.prepareStatement(sql);              
            ResultSet rs2 = pst.executeQuery();
            while(rs2.next()){
            billno.setText(rs2.getString(1));
            TextArea1.setText("Jid\tPrice\tJwellery Type");
        //jTextField7.setText();
       
        }
     
        
   
        
        
    }   catch (Exception ex) {
           
        }
    
    }
    private void metalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metalActionPerformed
        cur.setText("Current Price of "+metal.getSelectedItem().toString()+" :");
    }//GEN-LAST:event_metalActionPerformed

    private void grandtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grandtotalActionPerformed
    int count1=0;
    private void weightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightKeyReleased
        
    }//GEN-LAST:event_weightKeyReleased
    float gprice =0;
    float mprice =0;
    private void gstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gstKeyReleased
        
        float p = Float.parseFloat(oprice.getText());
        float g = Float.parseFloat(gst.getText());
         gprice = p*(g/100);       // Formula (Materila Price*(Gst Percentage/100))
     
    }//GEN-LAST:event_gstKeyReleased

    private void mchargeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mchargeKeyReleased
       float p = Float.parseFloat(oprice.getText());
       float m = Float.parseFloat(mcharge.getText());
       mprice = (p*(m/100));       // Formula - Materila price+(Materila Price*(making Percentage/100))
       float t = gprice+mprice+Float.parseFloat(oprice.getText());
       grandtotal.setText(Float.toString(t));
       
    }//GEN-LAST:event_mchargeKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    String id;
    private void gbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbillActionPerformed
        try
        {
           
            JOptionPane.showMessageDialog(null, "Added To Database");
            TextArea1.append("\n------------------------------------------------------------\nGrand Total : "+grandtotal1.getText()+"");
                
            String sql= "insert into bill values(?,?,?,?,?,?)";
                  System.out.println(conn);
                 
            pst=conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(billno.getText()));
            pst.setString(2, cdate.getText());
            pst.setString(3, cname.getText());
            pst.setString(4, cnumber.getText());
            pst.setString(5,String.valueOf(count1));
            pst.setString(6, grandtotal1.getText());
           
            
            
            
            
            pst.execute();
            count =0;
            JOptionPane.showMessageDialog(null,"Added");
            System.out.println("ok");
            
                
                
                JasperDesign j = JRXmlLoader.load("C:\\Users\\Desktop\\Desktop\\Project\\JewelleryShop\\src\\jewelleryshop\\Bill.jrxml");
                String q = "Select * from billdetails where billno = '"+billno.getText()+"'";
                HashMap p = new HashMap();
                p.put("grandtotal", grandtotal1.getText());
                JRDesignQuery uq = new JRDesignQuery();
                uq.setText(q);
                j.setQuery(uq);
                JasperReport jrp = JasperCompileManager.compileReport(j);
                JasperPrint jp = JasperFillManager.fillReport(jrp ,p,conn);
                JasperViewer.viewReport(jp, false);
                System.out.println("ok");
        
        
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_gbillActionPerformed
    void deduct()
    {
        String jqty ="";
        String nqty;
         try{
      
       
            String sql= "select qty from jewellery where jid ='"+jid.getSelectedItem().toString()+"'";
            pst=conn.prepareStatement(sql);              
            ResultSet rs2 = pst.executeQuery();
            if(rs2.next()){
            jqty = rs2.getString(1);
            System.out.println("qty is"+jqty);
           
        }
     if(Integer.parseInt(jqty)<=5)
            {
                JOptionPane.showMessageDialog(null,"You are Running OutofStock PLease Purchase Soon");
                jqty = String.valueOf(Integer.parseInt(jqty)-1);
                
                sql = "update jewellery set qty ='"+jqty+"' where jid ='"+jid.getSelectedItem()+"'";
                System.out.println(sql);
                pst=conn.prepareStatement(sql); 
                pst.execute();
                System.out.println("Done");
            }
            else if(Integer.parseInt(jqty)<2)
            {
                JOptionPane.showMessageDialog(null,"You are  Out of Stock Now PLease Purchase Soon");
                jqty = String.valueOf(Integer.parseInt(jqty)-1);
                
                sql = "update jewellery set qty ='"+jqty+"' where jid ='"+jid.getSelectedItem()+"'";
                System.out.println(sql);
                pst=conn.prepareStatement(sql); 
                pst.execute();
                System.out.println("Done");
            }
            else if(Integer.parseInt(jqty)==0)
            {
                JOptionPane.showMessageDialog(null,"You are Out of Stock ");
            }
            else if(Integer.parseInt(jqty)>5)
            {
                jqty = String.valueOf(Integer.parseInt(jqty)-1);
                
                sql = "update jewellery set qty ='"+jqty+"' where jid ='"+jid.getSelectedItem()+"'";
                System.out.println(sql);
                pst=conn.prepareStatement(sql); 
                pst.execute();
                System.out.println("Done");
            }
   
        
        
    }   catch (Exception ex) {
           System.out.println(ex);
        }
    }
    private void cbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuttonActionPerformed
        System.out.println(id);
        id ="Custom";
        System.out.println(id);
        cbutton.setSelected(true);
        rbutton.setSelected(false);
        jLabel8.setVisible(false);
        jid.setVisible(false);
        
        
    }//GEN-LAST:event_cbuttonActionPerformed
    int count =0;
    private void rbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttonActionPerformed
        
        count = count+1;
        
        cbutton.setSelected(false);
        rbutton.setSelected(true);
        jLabel8.setVisible(true);
        jid.setVisible(true);
        
       if(count>1)
       {
       
       }
       else
       {
           try{
      
       
            String sql= "select jid from jewellery";
            pst=conn.prepareStatement(sql);              
            ResultSet rs2 = pst.executeQuery();
            while(rs2.next()){
            jid.addItem(rs2.getString(1));
        
       
        }
       
    }   catch (Exception ex) {}
       }
        
        
        
    }//GEN-LAST:event_rbuttonActionPerformed

    private void jidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidActionPerformed
        
       
        {
            id = jid.getSelectedItem().toString();
        
        try{
      
            
            String sql= "select * from jewellery where jid ='"+id+"'";
            pst=conn.prepareStatement(sql);              
            ResultSet rs2 = pst.executeQuery();
            if(rs2.next()){
            otype.setText(rs2.getString("otype"));
            metal.setSelectedItem(rs2.getString("ometal"));
            weight.setText(rs2.getString("weight"));
        
        }
            
    }   catch (Exception ex) {
           System.out.println(ex);
        }
        }
        
    }//GEN-LAST:event_jidActionPerformed

    private void cpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpriceKeyReleased
      oprice.setText(Float.toString(Float.parseFloat(cprice.getText())*Float.parseFloat(weight.getText())));
    }//GEN-LAST:event_cpriceKeyReleased

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        try
        {
            String sql= "insert into billdetails values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                  System.out.println(conn);
                 
            pst=conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(billno.getText()));
            pst.setString(2, cdate.getText());
            pst.setString(3, cname.getText());
            pst.setString(4, cnumber.getText());
            pst.setString(5, otype.getText());
            pst.setString(6, metal.getSelectedItem().toString());
            pst.setString(7, cprice.getText());
            pst.setString(8, weight.getText());
            pst.setString(9, oprice.getText());
            pst.setString(10, gst.getText());
            pst.setString(11, mcharge.getText());
            pst.setString(12, grandtotal.getText());
            System.out.println(id);
           
            pst.setString(13, id);
            
            pst.execute();
            count1=count1+1;
            JOptionPane.showMessageDialog(null,"Added");
            System.out.println("After Add");
            total = total+Float.parseFloat(grandtotal.getText());
            grandtotal1.setText(String.valueOf(total));
            System.out.println(total);
            System.out.println("YOYo");
            
            if(id=="Custom")
            {
                System.out.println("Not deduct");
            }
            else
            {
                System.out.println("deduct");
                deduct();
            }
            TextArea1.append("\n"+id+"\t"+grandtotal.getText()+"\t"+otype.getText());
            cprice.setText("");
            oprice.setText("");
            gst.setText("");
            mcharge.setText("");
            grandtotal.setText("");
            
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_addActionPerformed

    private void grandtotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandtotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grandtotal1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        jLabel8.setVisible(false);
        jid.setVisible(false);
        getMaxId();
        cname.setText("");
        cnumber.setText("");
        weight.setText("");
        cprice.setText("");
        oprice.setText("");
        gst.setText("");
        mcharge.setText("");
        grandtotal.setText("");
        grandtotal1.setText("");
        cbutton.setSelected(false);
        
        rbutton.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
      Home h = new Home();
      h.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void cnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnumberKeyReleased
        if(cnumber.getText().length()>10)
        {
            JOptionPane.showMessageDialog(null,"Phone Number invalid");
            cnumber.setText("");
        }
    }//GEN-LAST:event_cnumberKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JButton add;
    private javax.swing.JTextField billno;
    private javax.swing.JRadioButton cbutton;
    private javax.swing.JTextField cdate;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnumber;
    private javax.swing.JTextField cprice;
    private javax.swing.JLabel cur;
    private javax.swing.JLabel cur1;
    private javax.swing.JLabel cur2;
    private javax.swing.JLabel cur3;
    private javax.swing.JLabel cur4;
    private javax.swing.JLabel cur5;
    private javax.swing.JLabel cur6;
    private javax.swing.JButton gbill;
    private javax.swing.JTextField grandtotal;
    private javax.swing.JTextField grandtotal1;
    private javax.swing.JTextField gst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox jid;
    private javax.swing.JTextField mcharge;
    private javax.swing.JComboBox metal;
    private javax.swing.JTextField oprice;
    private javax.swing.JTextField otype;
    private javax.swing.JRadioButton rbutton;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
